### ISSUE TITLE
Change VRM device ID

### ISSUE THREAD

**Issue by Jacke87** [freakent/dbus-mqtt-devices#29]
Hello everyone, it is possible to change the VRM Device ID.I use the Louis DB driver for my JKBMs and this driver, like this driver, uses the ID 1.The adapter is excellent, thank you for that

**Comment by freakent** [comment]
The device id is automatically generated and set by the dbus. That's why we need to have the registration step, so that we get a valid device id to publish values against. I don't believe you can change it. 

It's outside the scope of this driver, so maybe ask on the modifications forum in the Victron community.
